version: '3.8'
services:
  build:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - C:\Users\eagleye\RiderProjects\DynamicIsland:/app
    working_dir: /app
    command: |
      sh -c "dotnet restore DynamicIsland.sln &&
             dotnet publish DynamicIsland.sln -c Release -r win-x64 -o /app/binaries/windows &&
             dotnet publish DynamicIsland.sln -c Release -r osx-x64 -o /app/binaries/macos"
