version: '3.8'
services:
  build:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - C:\Users\eagleye\RiderProjects\DynamicIsland:/app
    working_dir: /app
    command: |
      sh -c "dotnet restore DynamicIsland.sln &&
             dotnet publish DynamicIsland.sln -c Release -r win-x64 --self-contained -p:PublishTrimmed=true -p:PublishSingleFile=true -o /app/binaries/windows &&
             dotnet publish DynamicIsland.sln -c Release -r osx-x64 --self-contained -p:PublishTrimmed=true -p:PublishSingleFile=true -o /app/binaries/macos"
              